config/routes.rb
Nootz::Application.routes.draw do
  resources :walls

  get 'list_item/crearnuevo/:id', to: 'list_items#crearnuevo'
  get '/nuevalista', to: 'lists#nuevalista'
  get '/mostrarlista/:id', to: 'lists#mostrarlista'

  get '/nuevanota', to: 'notes#nuevanota'
  get '/mostrarnota/:id', to: 'notes#mostrarnota'

  get '/nuevomuro', to: 'walls#nuevomuro'
  get '/mostrarmuro/:id', to: 'walls#mostrarmuro'

  resources :list_items

  resources :lists
  resources :users
  resources :notes
  resources :walls

  root :to => 'sessions#create'
  get 'notes/:id/visit' => 'notes#visit'
  get 'lists/:id/visit' => 'lists#visit'

	get '/login' => "sessions#create", as: "login"
	post '/login' => "sessions#create"
	get '/logout'=>"sessions#destroy", as: "logout"

end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :list_items
	scope :end_today, -> { where("limit_date = ? and visited = ?",DateTime.now.to_date,false)}
	scope :notDeleted, -> { where(deleted: false) }
	scope :deleted, -> { where(deleted: true) }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy,:visit]
def nuevalista
	@list = List.create(title:'Nueva lista', deleted:false, visited:false, limit_date:Date.today,wall_id: current_wall.id);
	respond_to do |format|
		 format.js
	end
end
def mostrarlista
	@list = List.find_by_id(params[:id])
	respond_to do |format|
		 format.js
	end
end

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.notDeleted
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
	
  end

  def visit
  @list.visited = true
   if @list.save
           respond_to do |format|
		 format.js
	end
      end
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list.limit_date = Time.now # MODO DEVELOPMENT
    @list.visited = false
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    #@list.destroy	A partir de ahora se marca como deleted en lugar de ser eliminados
    @list.update_attribute(:deleted, true)
    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :limit_date, :wall_id)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :limit_date %><br>
    <%= f.text_field :limit_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_show.html.erb
<div id="modallista" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">  <%= best_in_place @list, :title %></h4>
      </div>
      <div class="modal-body">
<div id="contenedorLista">
    <% @list.list_items.each do |li| %>
	<div class="input-group">
            <span class="input-group-addon">
		<%= best_in_place li, :checked, :type => :checkbox,  :collection => [raw("<input type='checkbox'></input>"),raw("<input type='checkbox' checked></input>")] %>
            </span>
	    <div class="listItemField">
		<%= best_in_place li, :content, :type => :input, :classes => 'form-control' %>
            </div>
	    <span class="listItemButton">
		<%= link_to list_item_path(li), method: :delete, class:"close" do %>
			<%= image_tag('x-mark-16.png') %>
		<% end %>
            </span>
	</div>
    <% end %>
</div>
      </div>
<div class="col-md-12">
	<button id="boton" type="button" class="btn btn-default">Nuevo elemento</button>
</div>
      <div class="modal-footer">
	 Fecha de recordatorio: <%= best_in_place @list, :limit_date, type: :date %>
	 <%= link_to 'Eliminar lista', @list, method: :delete, data: { confirm: '¿Realmente desea eliminar esta lista?' }, :class => "btn btn-danger" %>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
	$('#boton').click(function(){
	$.get('/list_item/crearnuevo/<%= @list.id %>');
});
</script>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Mis listas</h1>
<div class="row">
	<div class="col-md-offset-2 col-md-8">			
		<div class="col-md-offset-1 col-md-10">
			<div class="row">
				<div class="col-md-offset-5 col-md-5">
					<div class="btn-group">
  						<button  id="newlist" type="button" class="btn btn-default"><%= image_tag("add-list-24.png") %></button>
					</div>
				</div>
			</div>
			<%= yield %>

  <tbody>
    <% @lists.each do |list| %>
	<div class="btn btn-default muestralista" id="<%= list.id %>">
        <%= list.title %><br>
        <%= list.limit_date %>
        </div>
    <% end %>

<script>
$('body').on('hidden.bs.modal', '.modal', function () {
   document.location.reload();
});
$('#newlist').click(function(){
	$.get('/nuevalista');
});
$('.muestralista').click(function(e){
	$.get('/mostrarlista/'+e.target.id);
});
</script>

<div id="espaciomodales">
</div>

app/views/lists/mostrarlista.js.erb
$('#espaciomodales').html("<%= escape_javascript render('show') %>");
$('#modallista').modal('show');

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/nuevalista.js.erb
$('#espaciomodales').html("<%= escape_javascript render('show') %>");
$('#modallista').modal('show');

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "show" %>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/lists/visit.js.erb
$(".remove").parent().remove(); 
$('#nNotifications').html($('#nNotifications').html()-1);
$("[data-toggle='popover']").attr("data-content", $(".popover-content").html());