config/routes.rb
Nootz::Application.routes.draw do
  resources :walls

  get 'list_item/crearnuevo/:id', to: 'list_items#crearnuevo'
  get '/nuevalista', to: 'lists#nuevalista'
  get '/mostrarlista/:id', to: 'lists#mostrarlista'

  get '/nuevanota', to: 'notes#nuevanota'
  get '/mostrarnota/:id', to: 'notes#mostrarnota'

  get '/nuevomuro', to: 'walls#nuevomuro'
  get '/mostrarmuro/:id', to: 'walls#mostrarmuro'

  resources :list_items

  resources :lists
  resources :users
  resources :notes
  resources :walls

  root :to => 'sessions#create'
  get 'notes/:id/visit' => 'notes#visit'
  get 'lists/:id/visit' => 'lists#visit'

	get '/login' => "sessions#create", as: "login"
	post '/login' => "sessions#create"
	get '/logout'=>"sessions#destroy", as: "logout"

end

app/models/note.rb
class Note < ActiveRecord::Base
	scope :end_today, -> { where("limit_date = ? and visited = ?",DateTime.now.to_date,false)}
	scope :notDeleted, -> { where(deleted: false) }
	scope :deleted, -> { where(deleted: true) }	
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy,:visit]
def nuevanota
	@note = Note.create(title:'Nueva nota', deleted:false, content: 'Contenido de la nota', visited:false, limit_date:Date.today, wall_id: current_wall.id);
	respond_to do |format|
		 format.js
	end
end
def mostrarnota
	@note = Note.find_by_id(params[:id])
	respond_to do |format|
		 format.js
	end
end
  # GET /notes
  # GET /notes.json
  # El índice de notas se compone de las notas que no han sido marcadas como eliminadas
  def index
    @notes = Note.notDeleted
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  def visit
   @note.visited = true
   if @note.save
           respond_to do |format|
		 format.js
	end
      end
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.limit_date = Time.now # MODO DEVELOPMENT
    @note.visited = false
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    #@note.destroy	A partir de ahora se marca como deleted en lugar de ser eliminados
    @note.update_attribute(:deleted, true)
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content, :limit_date, :wall_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :limit_date %><br>
    <%= f.text_field :limit_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_show.html.erb
<div id="modalnota" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
 <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">    <%= best_in_place @note, :title %></h4>
      </div>

      <div class="modal-body">
           <%= best_in_place @note, :content, type: :textarea %>
      </div>

      <div class="modal-footer">
	 Fecha de recordatorio:   <%= best_in_place @note, :limit_date, type: :date %>
	 <%= link_to 'Eliminar nota', @note, method: :delete, data: { confirm: '¿Realmente desea eliminar esta nota?' }, :class => "btn btn-danger" %>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Mis notas</h1>
<div class="row">
	<div class="col-md-offset-2 col-md-8">			
		<div class="col-md-offset-1 col-md-10">
			<div class="row">
				<div class="col-md-offset-5 col-md-5">
					<div class="btn-group">
  						<button  id="newnote" type="button" class="btn btn-default"><%= image_tag("note-2-24.png") %></button>
					</div>
				</div>
			</div>
			<%= yield %>

  <tbody>
    <% @notes.each do |note| %>
	<div class="btn btn-default muestranota" id="<%= note.id %>">
        <%= note.title %><br>
        <%= note.limit_date %>
        </div>
    <% end %>

<script>
$('body').on('hidden.bs.modal', '.modal', function () {
   document.location.reload();
});
$('#newnote').click(function(){
	$.get('/nuevanota');
});
$('.muestranota').click(function(e){
	$.get('/mostrarnota/'+e.target.id);
});
</script>

<div id="espaciomodalesnotas">
</div>

app/views/notes/mostrarnota.js.erb
$('#espaciomodalesnotas').html("<%= escape_javascript render('show') %>");
$('#modalnota').modal('show');

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/nuevanota.js.erb
$('#espaciomodalesnotas').html("<%= escape_javascript render('show') %>");
$('#modalnota').modal('show');

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "show" %>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/notes/visit.js.erb
$(".remove").parent().remove(); 
$('#nNotifications').html($('#nNotifications').html()-1);
$("[data-toggle='popover']").attr("data-content", $(".popover-content").html());