config/routes.rb
Nootz::Application.routes.draw do
  resources :walls

  get 'list_item/crearnuevo/:id', to: 'list_items#crearnuevo'
  get '/nuevalista', to: 'lists#nuevalista'
  get '/mostrarlista/:id', to: 'lists#mostrarlista'

  get '/nuevanota', to: 'notes#nuevanota'
  get '/mostrarnota/:id', to: 'notes#mostrarnota'

  get '/nuevomuro', to: 'walls#nuevomuro'
  get '/mostrarmuro/:id', to: 'walls#mostrarmuro'

  resources :list_items

  resources :lists
  resources :users
  resources :notes
  resources :walls

  root :to => 'sessions#create'
  get 'notes/:id/visit' => 'notes#visit'
  get 'lists/:id/visit' => 'lists#visit'

	get '/login' => "sessions#create", as: "login"
	post '/login' => "sessions#create"
	get '/logout'=>"sessions#destroy", as: "logout"

end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
	belongs_to :list
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: [:show, :edit, :update, :destroy]

  def crearnuevo
	lid = params[:id]
	@list_item = ListItem.create(list_id: lid, checked: false, content:"")
  end
  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = ListItem.all
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @list_item = ListItem.new(list_item_params)
        respond_to do |format|
      if @list_item.save
        format.html { redirect_to @list_item, notice: 'List item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1
  # PATCH/PUT /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params.require(:list_item).permit(:checked, :content, :list_id)
    end
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/list_items/_form.html.erb
<%= form_for(@list_item) do |f| %>
  <% if @list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
      <% @list_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :checked %><br>
    <%= f.check_box :checked %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :list_id %><br>
    <%= f.number_field :list_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_items/_nuevoElementoLista.html.erb
<div class="input-group">
<span class="input-group-addon">
		<%= best_in_place @list_item, :checked, :type => :checkbox,  :collection => [raw("<input type='checkbox'></input>"),raw("<input type='checkbox' checked></input>")] %>
                
            </span>
	    <div class="listItemField">
		<%= best_in_place @list_item, :content, :type => :input, :classes => 'form-control' %>
            </div>
	    <span class="listItemButton">
		<%= link_to list_item_path(@list_item), method: :delete, class:"close" do %>
			<%= image_tag('x-mark-16.png') %>
		<% end %>
            </span>

</div>

app/views/list_items/crearnuevo.js.erb
$('#contenedorLista').append($("<%= escape_javascript render('nuevoElementoLista') %>"));

app/views/list_items/edit.html.erb
<h1>Editing list_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_item %> |
<%= link_to 'Back', list_items_path %>

app/views/list_items/index.html.erb
<h1>Listing list_items</h1>

<table>
  <thead>
    <tr>
      <th>Checked</th>
      <th>Content</th>
      <th>List</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @list_items.each do |list_item| %>
      <tr>
        <td><%= list_item.checked %></td>
        <td><%= list_item.content %></td>
        <td><%= list_item.list_id %></td>
        <td><%= link_to 'Show', list_item %></td>
        <td><%= link_to 'Edit', edit_list_item_path(list_item) %></td>
        <td><%= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List item', new_list_item_path %>

app/views/list_items/new.html.erb
<h1>New list_item</h1>

<%= render 'form' %>

<%= link_to 'Back', list_items_path %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Checked:</strong>
  <%= @list_item.checked %>
</p>

<p>
  <strong>Content:</strong>
  <%= @list_item.content %>
</p>

<p>
  <strong>List:</strong>
  <%= @list_item.list_id %>
</p>

<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', list_items_path %>